### PR TITLE
Use the "UTC" identifier for the TimeZone.UTC time zone

### LINKED ISSUE #474: TimeZone..of("UTC") isn't equal to TimeZone.UTC
It's very unintuitive that this assert fails.
```kotlin
assertEquals(TimeZone.UTC, TimeZone.of("UTC"))
```
I've re-discovered this fact multiple times when writing tests around datetime logic with time zones.

Presumably this is the same root cause as #222

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
Fixes #474

### CODE REVIEW

File: core/common/test/TimeZoneTest.kt [hunk 1]
```diff
@@ -16,7 +16,7 @@ class TimeZoneTest {
     fun utc() {
         val utc: FixedOffsetTimeZone = TimeZone.UTC
         println(utc)
-        assertEquals("Z", utc.id)
+        assertEquals("UTC", utc.id)
```
Comment (ilya-g) [inline core/common/test/TimeZoneTest.kt:19]: Can you add a check that TimeZone.UTC equals TimeZone.of("UTC")?
